[alias]
compile = "build --release"
run-server = "run --bin server data/world.json"
run-client-raw = "run --bin client -- --raw"
run-client-tui = "run --bin client"
run-client-gui = "run --bin client -- --gui"
lint = "clippy --all-targets --all-features -- -D warnings"
